-- AlterTable
ALTER TABLE "MaxLifts" ADD COLUMN     "benchpressHistory" DOUBLE PRECISION[] DEFAULT ARRAY[]::DOUBLE PRECISION[],
ADD COLUMN     "deadliftHistory" DOUBLE PRECISION[] DEFAULT ARRAY[]::DOUBLE PRECISION[],
ADD COLUMN     "overheadHistory" DOUBLE PRECISION[] DEFAULT ARRAY[]::DOUBLE PRECISION[],
ADD COLUMN     "squatHistory" DOUBLE PRECISION[] DEFAULT ARRAY[]::DOUBLE PRECISION[];
